# Generated by Django 3.0.4 on 2020-03-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('original_text', models.TextField()),
                ('summarized_text', models.CharField(max_length=10000)),
                ('category', models.CharField(blank=True, choices=[('healthcare', 'healthcare'), ('technology', 'technology'), ('science', 'science'), ('beauty', 'beauty'), ('entertainment', 'entertainment'), ('politic', 'politic'), ('culinary', 'culinary'), ('others', 'others')], default='NA', max_length=70, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
