# Generated by Django 3.0.4 on 2020-03-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('understand', '0006_result_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
