# Generated by Django 3.0.4 on 2020-03-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('understand', '0007_auto_20200309_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
